### ISSUE TITLE
Community Sub-directory auto-populate JSON

### ISSUE THREAD

**Issue by auxfuse** [auxfuse/hackathon-git-labs#102]
* Directory traversal to retrieve list of nested sub-directories of `/community` Directory
* populate `assets/data/communityPages.json` file based on above list

considerations about doing this at build level within repo (github action / YML file) or doing this in Client browser...

**Comment by auxfuse** [comment]
Hi @Aramantos 

The idea here is to consider using some sort of File Directory traversal that srapes the community sub-directory folder names and then adds them to the json file, `communitypages.json` here: 👉👉 https://github.com/auxfuse/hackathon-git-labs/blob/main/assets/data/communitypages.json

Something we had discussed in a previous call, was continuing along the trend of keeping this an automated process, if possible, without the need for our participants to do anything additional outside of the scope of the projects main purpose, learning version control. 😄

**Comment by auxfuse** [comment]
@Aramantos this has kind of been superceeded by a more recent PR from @seanyoung247 

It totally slipped my mind 🤦‍♂️ so we might park this one for now, and come back to it later as there is a lot of moving parts to consider here now. 🤜

**Comment by seanyoung247** [comment]
I'm not sure it's actually possible to do this purely front-end. To do a directory traversal you'd need a server side backend, there's not really anyway to do it with front end code. Unless there's some sort of github action I'm not thinking of. I spent some time trying to work that out when writing the first version of the showcase code and the best I could do was ping the community directory on each attempt.

**Comment by auxfuse** [comment]
Closing for now, will rethink the automation of this for future implementation! Thanks lads 🤜
