### ISSUE TITLE
Slideshow Transition & Structural Enhancement

### ISSUE THREAD

**Issue by auxfuse** [auxfuse/hackathon-git-labs#150]
[Details of enhancement](https://github.com/auxfuse/hackathon-git-labs/issues/64#issuecomment-1279750595)

@seanyoung247 🤜 Can you assign yourself to this! Silly Github won't let me assign you until you've commented on the Issue 😆

**Comment by seanyoung247** [comment]
@auxfuse It doesn't seem to let me assign myself, but I can comment instead :).

Planned changes and nice to haves:
- Convert slideshow to web component.
	- Use progressive enhancement to keep functionality if component fails
- Fix transitions issue
	- Add alternative animations for slide transitions

Probably more as I think of them...

**Comment by auxfuse** [comment]
Yeah seems silly, but you have to actually comment as a form of request to be then applicable as a assignee. 🙄😂

**Comment by auxfuse** [comment]
Closing to suit massive PR #155 👏 Thanks again @seanyoung247 🤜
