### ISSUE TITLE
Custom 404 Error handler Page

### ISSUE THREAD

**Issue by auxfuse** [auxfuse/hackathon-git-labs#48]
Create custom 404 error handler page:
* emulate frontend design of `index.html`
* if participant only submits basic PR then this 404 should throw. With that in mind, consider adding wording and context to that affect...

"Wait! This page does not exist...either the participant hasn't added a custom creation yet, or you have tried to find a page that literally isn't here. ❌❌❌" etc etc

**Comment by auxfuse** [comment]
Closing to satisfy PR #60 from @andrewdempsey2018 🤜🤜

**Comment by andrewdempsey2018** [comment]
I have reopened this as the page is not rendering properly on the deployed version. Looks like the 'assets' folder is not being targeted properly. Currently it is looking for images / CSS at:

https://hackathon-gitlabs.studio/community/assets/images/

https://hackathon-gitlabs.studio/community/assets/css/

Solution would be to add appropriate '../' where assets are being loaded
