### ISSUE TITLE
Random Showcase of Community Participants

### ISSUE THREAD

**Issue by auxfuse** [auxfuse/hackathon-git-labs#64]
A section that on load showcases a random 5 members that have added a custom directory
* Consider checks to ensure that the participant has added a custom directory
* 5 members shown at any time? Considerations for less or more...
* Should follow along to the current style of the project
* Vanilla only! This means no Frameworks 😉😉 (I mean we want this to be a challenge right)
* This section could be on an alternaitve HTML page, it does not have to be contained on the `index.html` although we don't mind either

Feel free to develop this and showcase the functionality first, and then the styling can be picked up by someone else, or you, in an additional PR. 🤜

**Comment by seanyoung247** [comment]
Still looking for someone to do this?

**Comment by andrewdempsey2018** [comment]
Go for it Sean

**Comment by seanyoung247** [comment]
I'd be happy to give it a bash if I can be assigned

**Comment by andrewdempsey2018** [comment]
@seanyoung247 Done, good luck!

**Comment by auxfuse** [comment]
Thanks @seanyoung247 Awesome to see you jump on board with us on this 😄 🤜

**Comment by seanyoung247** [comment]
I've been meaning to have a look for awhile. What are you expecting for a showcase? At the moment I'm just generating cards like on the main page.

**Comment by auxfuse** [comment]
Random showcase of 5? These don't have to be rendered on the `index.html` and we could potentially add this as a small featurette on another html page coming down the track etc.

**Comment by seanyoung247** [comment]
I mean what are you thinking of displaying? At the moment I have a bit of code that creates random cards:

**Comment by auxfuse** [comment]
Hi Sean, that's perfect man! Genuinely. I guess the end-result would be to have the showcase lead the charge or close out a page about the platform itself. Think of it like a quasi-group of testimonials 😛 Just a random display of 5 people from the `community.json` data.

Thanks so much for the work lad 🤜 Really happy to see you contribute to it. 🙌

**Comment by auxfuse** [comment]
I would love to see you contribute your own custom creation to the Community directory too by the way 🤜 The more unique and brilliant creations we have in this, the better! 😄

**Comment by seanyoung247** [comment]
Thanks :). I've got an idea for a custom page. Was thinking of having a crack at that after the showcase cards are styled.

**Comment by auxfuse** [comment]
@seanyoung247 I'm happy to close this out now my man! You've done an exceptional job here and have blown all of my expectations out of the water with your work. 🤜 Thank you so fucking much! 👏

**Comment by seanyoung247** [comment]
Awesome :). There's a minor issue with the transition animation that I want to fix. The best way to do it would be a bit of a structural overhaul though. I want to learn web components so I'll be looking to re-implement the slideshow as a web component and fix the animation at the same time if that's ok. Might take a bit though, since I'm teaching myself web components as I go along.

**Comment by auxfuse** [comment]
We can open a new issue for the enhancement of the current solution @seanyoung247 but damn am I looking forward to seeing it in action 🤜 This project will continue to be open source even after Hacktoberfest (it has been since March 😆 ) so any time at all, and definitely no rush 🙌
