### ISSUE TITLE
Accessibility Enhancements

### ISSUE THREAD

**Issue by auxfuse** [auxfuse/hackathon-git-labs#66]
HTML pages need Accessibility enhancement
* Should follow W3C Accessibility standards ( https://www.w3.org/WAI/standards-guidelines/ ) e.g: tab-index / contrast issues etc

**Comment by puritybirir** [comment]
Hey @auxfuse please assign me to this issue. I am an accessibility champion and would love to work on this issue.

**Comment by auxfuse** [comment]
Done 😄 Looking forward to seeing what you can bring to the project @puritybirir 🤜 Thanks for jumping in.

**Comment by puritybirir** [comment]
Looking forward to this as well

**Comment by puritybirir** [comment]
With regard to contrast, there are no outstanding issues. The contrast ratio is 8.59: 1

<img width="345" alt="Screenshot 2022-10-03 at 11 42 21 AM" src="https://user-images.githubusercontent.com/19901599/193541319-61f2315f-ee7a-426b-95f3-12f6d7d150bb.png">

The majority of the accessibility issues are on the card element itself. Looking at that now.

**Comment by puritybirir** [comment]
> Hi @puritybirir Are you happy for us to close this Issue out? As more and more primary pages get added to the site map, we will open up additional PRs of this nature.

Yes

**Comment by auxfuse** [comment]
Closing to suit PR #85 - Thanks for everything @puritybirir 🤜 Legend!
