### ISSUE TITLE
`basic.md` Guide translated into HTML page

### ISSUE THREAD

**Issue by auxfuse** [auxfuse/hackathon-git-labs#68]
`basic.md` guide to be translated into easy-to-follow HTML page
* styled in terms of Project current theme
* semantic use of HTML elements
* Accesible and intuitive
* Use of Emoji's is absolutely allowed 😆

**Comment by ginabeki** [comment]
Hey, @auxfuse I'd like to work on this. I'm very comfortable with HTML and also have sound UI/UX logic. I'll also ensure that the page meets accessibility standards.

**Comment by auxfuse** [comment]
Hi @ginabeki Done! Great to have you on board. Thanks so much 🤜

**Comment by ginabeki** [comment]
Hi @auxfuse. Glad to be working on this

**Comment by auxfuse** [comment]
Closing this to suit PR #95 👏 👏
