### ISSUE TITLE
`intermediate.md` translated into HTML page

### ISSUE THREAD

**Issue by auxfuse** [auxfuse/hackathon-git-labs#69]
`intermediate.md` guide to be translated into easy-to-follow HTML page

* styled in terms of Project current theme
* semantic use of HTML elements
* Accesible and intuitive
* Use of Emoji's is absolutely allowed 🎁 
* link to `basic.html` needed to allow for flow of document and process

**Comment by Harsh-Singh-Rajput** [comment]
@auxfuse can I work on this?
Do you want to replicate the contents exactly which are in the intermediate.md?

**Comment by tejasjaiswal07** [comment]
Hey @auxfuse, can you please assign me to this project as I would love it contribute to this project.
Thank you!

**Comment by auxfuse** [comment]
Hi @Harsh-Singh-Rajput yes please. 😄 The `intermediate.md` file is basically a Script that we use for our students anyway, just typed in Markdown. If you could format that into a HTML Document and place it in the root folder, that would be great. I've assigned this to you as the first person who commented for it 🤜

**Comment by auxfuse** [comment]
@Harsh-Singh-Rajput Please make sure to use as much of the current CSS as possible, and to keep the file Framework-less. This means we will not accept any Frontend Framework inclusions onto the site. For example, bootstrap/materialize/tailwind etc.

**Comment by Harsh-Singh-Rajput** [comment]
> Hi @Harsh-Singh-Rajput yes please. 😄 The `intermediate.md` file is basically a Script that we use for our students anyway, just typed in Markdown. If you could format that into a HTML Document and place it in the root folder, that would be great. I've assigned this to you as the first person who commented for it 🤜

Thanks @auxfuse for assigning this to me . I will do it with css only without using any CSS frameworks.
So I will make the HTML File which looks like to the output of the intermediate markdown file😀

**Comment by auxfuse** [comment]
Closing this to suit PR #93 👏 👏
